### ISSUE TITLE
Traceback (most recent call last):   File ".\lpa.py", line 95, in <module>     lpa(g)   File ".\lpa.py", line 58, in lpa

### ISSUE THREAD

**Issue by wustczx** [anatman-xx/lpa#2]
Excuse me, I run python lpa.py. error:
PS C:\Users\admin\Desktop\lpa\lpa> python .\lpa.py
loop 1
Traceback (most recent call last):
  File ".\lpa.py", line 95, in <module>
    lpa(g)
  File ".\lpa.py", line 58, in lpa
    neighbor_weight = graph.edges[node][neighbor]['weight']
  File "D:\Python35\lib\site-packages\networkx\classes\reportviews.py", line 930, in __getitem__
    return self._adjdict[u][v]
KeyError: '2'
How can I do? thank you.

**Comment by hellozm** [comment]
> 
> 
> Excuse me, I run python lpa.py. error:
> PS C:\Users\admin\Desktop\lpa\lpa> python .\lpa.py
> loop 1
> Traceback (most recent call last):
> File ".\lpa.py", line 95, in
> lpa(g)
> File ".\lpa.py", line 58, in lpa
> neighbor_weight = graph.edges[node][neighbor]['weight']
> File "D:\Python35\lib\site-packages\networkx\classes\reportviews.py", line 930, in **getitem**
> return self._adjdict[u][v]
> KeyError: '2'
> How can I do? thank y

> 
> 
> Excuse me, I run python lpa.py. error:
> PS C:\Users\admin\Desktop\lpa\lpa> python .\lpa.py
> loop 1
> Traceback (most recent call last):
> File ".\lpa.py", line 95, in
> lpa(g)
> File ".\lpa.py", line 58, in lpa
> neighbor_weight = graph.edges[node][neighbor]['weight']
> File "D:\Python35\lib\site-packages\networkx\classes\reportviews.py", line 930, in **getitem**
> return self._adjdict[u][v]
> KeyError: '2'
> How can I do? thank you.

You need to modify and delete some code

**Comment by webbrain-one** [comment]
Hi! 👋

Thanks for reporting this error. I've opened a pull request to address this issue: #3.

This PR fixes the `KeyError` by safely handling access to edge weights when they might be missing or undefined during the loop. Please take a look at the PR and let me know if this resolves the problem for you.

Thanks again for your feedback!
